# Generated by Django 5.1.2 on 2024-12-08 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_usertraining'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertraining',
            name='json_field',
            field=models.TextField(),
        ),
    ]
